site_name: AI/ML Companion Site
site_url: https://mcklay.github.io/MLops-Project-Handbook/
site_author: Clay Mark Sarte
site_description: Two-book documentation site combining project-based and tooling-based AI/ML guides.

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  hide:
    - toc

nav:
  - Introduction: index.md

  - "📘 Mastering AI/ML Projects":
      - "&nbsp; Table of Contents": book_project_budget/TOC.md
      - "&nbsp;&nbsp; Preface": book_project_budget/Preface.md
      - "&nbsp;&nbsp; 📖 Part I: Foundations": book_project_budget/Book1_PartI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 1": book_project_budget/Book1_chapter1.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 2": book_project_budget/Book1_chapter2.md

      - "&nbsp;&nbsp; 📖 Part II: AI/ML Project Development": book_project_budget/Book1_PartII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 3": book_project_budget/Book1_chapter3.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 4": book_project_budget/Book1_chapter4.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 5": book_project_budget/Book1_chapter5.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 6": book_project_budget/Book1_chapter6.md

      - "&nbsp;&nbsp; 📖 Part III: Free-Tier Services": book_project_budget/Book1_PartIII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 7": book_project_budget/Book1_chapter7.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 8": book_project_budget/Book1_chapter8.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 9": book_project_budget/Book1_chapter9.md

      - "&nbsp;&nbsp; 📖 Part IV: Cost-Optimized Strategies": book_project_budget/Book1_PartIV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 10": book_project_budget/Book1_chapter10.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 11": book_project_budget/Book1_chapter11.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 12": book_project_budget/Book1_chapter12.md

      - "&nbsp;&nbsp; 📖 Part V: Recommendations": book_project_budget/Book1_PartV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 13": book_project_budget/Book1_chapter13.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 14": book_project_budget/Book1_chapter14.md

  - "📘 AI/ML Project Toolkit":
      - "&nbsp; Table of Contents": book_toolkit/TOC.md
      - "&nbsp;&nbsp; Preface": book_toolkit/Preface.md
      - "&nbsp;&nbsp; 📖 Part I: Development & Deployment Essentials": book_toolkit/Book2_PartI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 1": book_toolkit/Book2_chapter1_CI_CD.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 2": book_toolkit/Book2_chapter2_FastAPI.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 3": book_toolkit/Book2_chapter3_GradioReact.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 4": book_toolkit/Book2_chapter4_Docker.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 5": book_toolkit/Book2_chapter5_ENV_Files.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 6": book_toolkit/Book2_chapter6_Railway_HF_Render.md

      - "&nbsp;&nbsp; 📖 Part II: AI/ML-Specific Tooling": book_toolkit/Book2_PartII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 7": book_toolkit/Book2_chapter7_GPU_Runtime.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 8": book_toolkit/Book2_chapter8_Transformers.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 9": book_toolkit/Book2_chapter9_Inference_vs_Training.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 10": book_toolkit/Book2_chapter10_Replicate_Stability_API.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 11": book_toolkit/Book2_chapter11_Prompt_Engineering.md

      - "&nbsp;&nbsp; 📖 Part III: Scalability, Monitoring & Security": book_toolkit/Book2_PartIII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 12": book_toolkit/Book2_chapter12_RateLimit_Cooldowns.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 13": book_toolkit/Book2_chapter13_Debugging.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 14": book_toolkit/Book2_chapter14_Authentication.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 15": book_toolkit/Book2_chapter15_CI-CD_&_SaaS.md

      - "&nbsp;&nbsp; 📖 Part IV: Mindset & Philosophy": book_toolkit/Book2_PartIV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 16": book_toolkit/Book2_chapter16_Why_Tools_Matter.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 17": book_toolkit/Book2_chapter17_Shipping.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McKlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/clay-mark-sarte-283855147/
